config/routes.rb
Kbk::Application.routes.draw do
  devise_for :users

  root to: 'investigations#index'

  resources :documents do
    resource :star, only: [:create, :destroy], controller: 'favourites'

    resources :snapshots, only: :create
    resources :attachements, controller: 'document_attachements', only: [:create, :destroy]
  end

  resources :videos, :links, only: [:create, :destroy]

  resources :photos, only: [:create, :destroy] do
    collection do
      post :finalize
    end
  end

  resources :attachements, controller: 'document_attachements', only: [:create, :destroy]

  resources :investigations do
    resource :star, only: [:create, :destroy], controller: 'favourites'
    member do
      put :publish
      put :unpublish
    end
  end

  resources :snapshots, only: [:create, :destroy, :update] do
    collection do
      post :sort
    end
  end

  resources :organizations, except: :show

  resources :users, except: :show do
    member do
      get :unlock
    end
  end

end

app/models/investigation.rb
require 'concerns/safe_destroy'

class Investigation < ActiveRecord::Base
  include SafeDestroy

  extend Enumerize

  enumerize :status, in: [:active, :success, :failure], default: :active, scope: true, predicates: true

  enumerize :project_kind, in: [:rospil, :investigation], default: :investigation

  validates :title, presence: true, uniqueness: true
  validates :user, presence: true

  belongs_to :user
  belongs_to :latest_document, class_name: 'Document'

  has_many :documents

  has_many :videos, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :links, dependent: :destroy

  has_many :organizations, -> { uniq }, through: :documents
  has_many :timeline_entries, dependent: :destroy

  scope :published, -> { where("published_until IS NOT NULL") }
  scope :textual, lambda{|needle|
    needle = "%#{needle}%"
    fields = [
      arel_table[:title],
      arel_table[:description],
      Document.arel_table[:title],
      Document.arel_table[:description],
      Organization.arel_table[:name]
    ]

    condition = fields.shift.matches(needle)
    fields.each{|f| condition = condition.or(f.matches needle)}

    includes(:latest_document, :organizations).where(condition)
  }

  def publish
    @publish ||= InvestigationPublish.new(self)
  end

  def cache_latest_document!
    update_attribute(:latest_document, documents.latest.first)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  enumerize :role, in: [:lawyer, :admin], default: :lawyer, predicates: true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :lockable, :recoverable

  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true

  has_one :author
  has_many :documents
  has_many :favourites
  has_many :investigations

  after_create :create_author

  def active_for_authentication?
    super && !blocked?
  end

  private

  def create_author
    Author.create!(name: name, user_id: id)
  end
end

app/controllers/investigations_controller.rb
class InvestigationsController < ApplicationController

  before_filter :authenticate_user!, except: [:show, :index]
  before_filter :load_and_check_permissions, only: :show

  respond_to :html

  def index
    if user_signed_in?
      index_for_authorized
    else
      index_for_anonymous
    end

    render layout: 'index'
  end

  def edit
    @investigation = find_investigation
  end

  def new
    @investigation = Investigation.new
  end

  def show
    @investigation = find_investigation.decorate

    @documents = @investigation.documents.latest
    @timeline_entries = @investigation.timeline_entries.latest

    if !user_signed_in?
      @documents = @documents.where("document_date <= ?", @investigation.published_until)
      @timeline_entries = @timeline_entries.where("entry_date <= ?", @investigation.published_until)
    end

    respond_to do |format|
      format.html
      if user_signed_in?
        format.json { render json: @investigation.as_json(include: { documents: { only: [:id, :title] } }, root: false) }
      end
    end
  end

  def publish
    investigation = find_investigation
    flash[:notice] = if investigation.publish.update(params[:date])
      "Расследование опубликовано"
    else
      "Расследование не опубликовано"
    end

    redirect_to investigation
  end

  def unpublish
    investigation = find_investigation
    investigation.publish.cancel

    redirect_to investigation, notice: "Расследование скрыто"
  end

  def update
    @investigation = find_investigation
    @investigation.update(investination_params)

    respond_with @investigation
  end

  def create
    @investigation = current_user.investigations.create(investination_params)
    respond_with @investigation
  end

  def destroy
    investigation = find_investigation
    if investigation.user == current_user || current_user.admin?
      investigation.safe_destroy
    end

    redirect_to :investigations
  end

  private

  def set_collections
    @favourite_ids = current_user.favourites.investigations.pluck(:entry_id)
    @organizations = Organization.all.pluck(:name, :id)
    @users = User.all.pluck(:name, :id)
  end

  def investination_params
    params.require(:investigation).permit(:description, :title, :organization_id, :user_id, :status)
  end

  def find_investigation
    Investigation.find(params[:id])
  end

  def load_and_check_permissions
    @investigation = find_investigation
    if !user_signed_in? && @investigation.published_until.blank?
      redirect_to new_user_session_path
    end
  end

  def index_for_authorized
    set_collections

    @filter = InvestigationsFilter.new(params[:f], current_user, @favourite_ids)
    @sorter = InvestigationsSorter.new(params[:s])
    @investigations = @sorter.apply(@filter.apply)

    @investigations = @investigations.page(params[:page])
  end

  def index_for_anonymous
    @investigations = Investigation.published.page(params[:page])
  end
end

app/helpers/investigations_helper.rb
module InvestigationsHelper
end

app/views/investigations/_entry.html.slim
= render "investigations/entries/#{entry.resource_type.underscore}", entry: entry, prev_entry: prev_entry, next_entry: next_entry

- if @investigation.publish.active? && @investigation.published_until < entry.entry_date && (next_entry.blank? || @investigation.published_until >= next_entry.entry_date )
  .thread-document-published-separator
    | Опубликовано до этого момента

app/views/investigations/_form.html.slim
= simple_form_for @investigation do |f|
    fieldset.investigation-properties
      | Статус дела:
      = f.input :status,
              :collection => [['active', 'В процессе'], ['success', 'Решено'], ['failure', 'Окончательный отказ']],
              :label_method => :last,
              :value_method => :first,
              :as => :radio_buttons,
              :checked => @investigation.status,
              :required => false,
              :label => false

    = f.input :title, as: :string, input_html: { size: 50 }
    = f.input :description, as: :text
    = f.input :project_kind, include_blank: false

    .actions
      = f.submit class: 'big-green-button is-compact', value: 'Сохранить изменения'

      - if @investigation.persisted?
        .investigation-form-cancel
          a href=investigation_path(@investigation)
            | Отмена
      .investigation-form-delete
        a href='#'
          | Как удалить это дело?

app/views/investigations/_thread.html.slim
.investigations-thread
  - @timeline_entries.each_with_index do |entry, index|
    = render 'entry', entry: entry, prev_entry: @timeline_entries[index - 1], next_entry: @timeline_entries[index + 1]

app/views/investigations/edit.html.slim
article.is-form.is-investigation-form

  = link_to 'Вернуться к списку дел', investigations_path, class: 'link-back'

  h1.form-title
    | Редактирование дела

  = render 'form'

.investigation-form-side

app/views/investigations/index.html.slim
- content_for :add do
  .big-green-button.add-new-object.is-new-investigation
    = link_to 'Добавить дело', new_investigation_path

- if user_signed_in?
  .list-filter.investigations-filter
    = simple_form_for @filter.filterer, url: investigations_path, as: :f, method: :get do |f|
      fieldset.list-filter-slider-block@slider
        = image_tag 'icons/slider.png', role: 'handle', class: 'handle', height: 28, width: 28
        = f.input :status,
                :as => :radio_buttons,
                :required => false,
                :label => false,
                :wrapper_class => 'radio-slider list-filter-slider' do

          = f.collection_radio_buttons :status, [['', 'Все дела'], ['active', 'В процессе'], ['success', 'Решено'], ['failure', 'Отказ']], :first, :last, item_wrapper_tag: nil do |b|
            - content_tag :span, role: 'entry', class: "radio-slider-item is-#{b.value}" do
              - b.radio_button + b.label

        = f.input :props,
                :as => :check_boxes,
                :required => false,
                :label => false,
                :wrapper_class => 'list-filter-filter-buttons' do |b|
          = f.collection_check_boxes  :props, [['marked', 'Отмеченные'], ['no_answer', 'Нет ответа'], ['published', 'Опубликованные']], :first, :last, item_wrapper_tag: nil do |b|
            - content_tag :span, class: "is-#{b.value}" do
              - b.check_box + b.label(class: "toggled-button filter-button")

        .list-filter-search-form
          = f.input :title, as: :string, required: false, label: false, placeholder: 'Поиск дел', input_html: {role: 'submitter'}
          = f.submit value: ''

      fieldset.list-filter-form-block
        = f.input :organization_id, as: :custom_select, required: false, label: 'Организация в деле', collection: @organizations
        = f.input :user_id, as: :custom_select, required: false, label: 'Автор', collection: @users
        = f.input :latest_document, as: :date_range, label: 'Последний документ', required: false
        = f.input :creation_period, as: :date_range, label: 'Дело создано', required: false
        = f.input :project_kind, as: :custom_select, label: 'Проект', required: false, collection: Investigation.project_kind.options

- if @filter
  .list-filter-total
    | Показано дел: #{@filter.counters.size}


table.index-list.cases-list
  thead
    tr
      th.is-star
      th.is-color
        .icon-wrapper
      th.is-title class=sort_class?('investigations.title')
        a href=sort_by('investigations.title')
          | Дело
      th.is-organizations
        | Организации в деле
      th.is-latest-document class=sort_class?('latest_document')
        a href=sort_by('latest_document')
          | Последний документ
      th.is-created class=sort_class?('investigations.created_at')
        a href=sort_by('investigations.created_at')
          | Создано
      th.is-closed class=sort_class?('closed_at')
        a href=sort_by('closed_at')
          | Закрыто

  tbody
    - @investigations.each do |e|
      tr class="is-#{e.status}"
        td.is-star
          - if @favourite_ids
            = star e, 'investigations', @favourite_ids.include?(e.id)
        td.is-color
        td.is-title
          a.table-case-title href=investigation_path(e)
            = e.title
          .table-case-info
            | #{e.documents.size} #{Russian.p(e.documents.size, 'документ', 'документа', 'документов')}: #{e.documents.incoming.size} #{Russian.p(e.documents.incoming.size, 'входящий', 'входящих', 'входящих')}, #{e.documents.outgoing.size} #{Russian.p(e.documents.outgoing.size, 'исходящий', 'исходящих', 'исходящих')}
        td.is-organizations
          - e.organizations.each do |o|
            .table-document-organization= o.name
        td.is-latest-document
          - if e.latest_document && (user_signed_in? || e.latest_document.published?)
            = l e.latest_document.document_date, format: :short
            .table-document-description
              = e.latest_document.title
          - else
            span.spacer
              | &mdash;
        td.is-created
          = l e.created_at.to_date, format: :short
        td.is-closed
          - if e.closed_at
            = l e.closed_at, format: :short
          - else
            span.spacer
              | &mdash;

= paginate @investigations

app/views/investigations/new.html.slim
article.is-form.is-investigation-form

  = link_to 'Вернуться к списку дел', investigations_path, class: 'link-back'

  h1.form-title
    | Добавление дела

  = render 'form'

.investigation-form-side

app/views/investigations/show.html.slim
article.is-investigation
  = link_to 'Дела', investigations_path, class: 'link-back'

  h1.investigation-title
    = @investigation.title
    - if @timeline_entries.any?
      span.investigation-date
        = l @timeline_entries.first.entry_date

  .investigation-description= @investigation.description
  .investigation-description
    - if @investigation.published_until?
      | Дело опубликовано до #{l(@investigation.published_until)}
    - else
      | Дело не опубликовано

  .investigation-status
    | Статус:&nbsp;
    = t(@investigation.status, scope: "models.investigation.statuses")
    - if false
      a.investigation-status-edit@edit href="#"

  .investigation-display-mode
    label.is-thread
      = radio_button_tag 'display-mode', 'thread', true, data: { content: 'thread_view'}, role: 'content_togle'
      span
        | Цепочкой
    label.is-table
      = radio_button_tag 'display-mode', 'table', false, data: { content: 'table_view' }, role: 'content_togle'
      span
        | Таблицей

  .investigation-thread-view role="thread_view toggable_content"
    = render 'thread'

  .investigation-table-view role="table_view toggable_content"
    = render 'documents/documents_table'

- if user_signed_in?
  .investigation-side
    ul.investigation-controls
      li.investigation-control.is-edit
        = link_to "Редактировать", edit_investigation_path(@investigation), class: "action"

      li.investigation-control.is-connect
        = link_to "Добавить документ", new_document_path(investigation_id: @investigation.id), class: "action"

      li.investigation-control.is-connect
        = link_to "Добавить видео", "javascript:;", class: "action", role: "open-add-model", data: {media_type: "video"}
      li.investigation-control.is-connect
        = link_to "Добавить ссылку", "javascript:;", class: "action", role: "open-add-model", data: {media_type: "link"}
      li.investigation-control.is-connect
        = link_to "Добавить фото", "javascript:;", class: "action", role: "open-add-model", data: {media_type: "photo"}

      li.investigation-control.is-publish
        = link_to "Опубликовать", "javascript:;", role: "publish-link", class: "action"

        .side-control-popover
          = form_tag publish_investigation_path(@investigation), method: :put do
            p Приложенные файлы будут опубликованы "как есть".
            = text_field_tag "date", (@investigation.published_until || Date.current).strftime("%d.%m.%Y"), role: "datepicker"
            = submit_tag "Применить"
          - if @investigation.publish.active?
            .popover-linked
              = link_to "Снять с публикации", [:unpublish, @investigation], method: :put

      - if @investigation.user == current_user || current_user.admin?
        li.investigation-control.is-delete
          = link_to 'Удалить дело', investigation_path, method: :delete, data: {confirm: "Вы уверены?"}, class: "action"

- %w(video link photo).each do |media_type|
  = render "investigations/modals/new_#{media_type}"