config/routes.rb
Kbk::Application.routes.draw do
  devise_for :users

  root to: 'investigations#index'

  resources :documents do
    resource :star, only: [:create, :destroy], controller: 'favourites'

    resources :snapshots, only: :create
    resources :attachements, controller: 'document_attachements', only: [:create, :destroy]
  end

  resources :videos, :links, only: [:create, :destroy]

  resources :photos, only: [:create, :destroy] do
    collection do
      post :finalize
    end
  end

  resources :attachements, controller: 'document_attachements', only: [:create, :destroy]

  resources :investigations do
    resource :star, only: [:create, :destroy], controller: 'favourites'
    member do
      put :publish
      put :unpublish
    end
  end

  resources :snapshots, only: [:create, :destroy, :update] do
    collection do
      post :sort
    end
  end

  resources :organizations, except: :show

  resources :users, except: :show do
    member do
      get :unlock
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  enumerize :role, in: [:lawyer, :admin], default: :lawyer, predicates: true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :lockable, :recoverable

  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true

  has_one :author
  has_many :documents
  has_many :favourites
  has_many :investigations

  after_create :create_author

  def active_for_authentication?
    super && !blocked?
  end

  private

  def create_author
    Author.create!(name: name, user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_user, only: [:destroy, :update, :edit, :unlock]
  before_filter :check_permissions, except: :index

  respond_to :html

  def index
    @sorter = UsersSorter.new(params[:s])
    @users = @sorter.apply(User.all).page(params[:page])

    render layout: 'index'
  end

  def new
    @user = User.new
  end

  def unlock
    @user.unlock_access!
    redirect_to action: :index
  end

  def create
    @user = User.new(user_params)
    signup = Signup.new(@user)

    if signup.save
      redirect_to :users, notice: "Пользователю отправлено письмо с паролем"
    else
      render :new
    end
  end

  def update
    @user.update(user_params)

    respond_with @user, location: :users
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    user = params.require(:user)
    user = if current_user.admin?
      user.permit!
    else
      user.permit(:email, :password, :password_confirmation)
    end

    if user[:password].blank?
      user.delete("password")
      user.delete("password_confirmation")
    end
    user
  end

  def check_permissions
    unless current_user.admin? || @user == current_user
      redirect_to :root
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  - if current_user.admin?
    = f.input :name, input_html: { size: 50 }
  = f.input :email, input_html: { size: 50 }
  - if current_user.admin?
    = f.input :role, include_blank: false
    = f.input :blocked
  - if f.object.persisted?
    = f.input :password, input_html: { role: 'password-input', size: 50 }
    = f.input :password_confirmation, input_html: { size: 50 }

  .actions
    = f.submit 'Сохранить изменения', class: 'big-green-button is-compact'

app/views/users/edit.html.slim
article.is-form

  = link_to 'Вернуться к списку пользователей', users_path, class: 'link-back'

  h1.form-title.is-document-edit
    | Редактирование пользователя

  = render 'form'

app/views/users/index.html.slim
- if current_user.admin?
  - content_for :add do
    .big-green-button.add-new-object.is-new-user
      = link_to 'Создать пользователя', new_user_path

table.index-list.users-list
  thead.index-list-header
    tr
      th.is-name class=sort_class?('name')
        a href=sort_by('name')
          | Имя
      th.is-email class=sort_class?('email')
        a href=sort_by('email')
          | Почта
      th.is-documents-count class=sort_class?('documents_count')
        a href=sort_by('documents_count')
          | Документов
      th.is-role class=sort_class?('role')
        a href=sort_by('role')
          | Роль
      th.is-activity class=sort_class?('last_sign_in_at')
        a href=sort_by('last_sign_in_at')
          | Последняя активность

  tbody
    - @users.each do |user|
      tr class=('is-locked' if user.access_locked?)
        td.is-name
          - if current_user.admin?
            a.table-document-name href=edit_user_path(user)
              span
                = user.name
          - else
            = user.name
          - if user.access_locked?
            | &nbsp;
            small
              | (
              = link_to "разблокировать", unlock_user_path(user)
              | )
        td.is-email
          = user.email
        td.is-documents-count
          = user.documents_count
        td.is-role
          = user.role.text
        td.is-activity
          - if user.last_sign_in_at
            = l user.last_sign_in_at.to_date, format: :short
          - else
            span.spacer
              | &mdash;

= paginate @users

app/views/users/new.html.slim
article.is-form

  = link_to 'Вернуться к списку пользователей', users_path, class: 'link-back'

  h1.form-title.is-document-edit
    | Добавление пользователя

  = render 'form'