config/routes.rb
Kbk::Application.routes.draw do
  devise_for :users

  root to: 'investigations#index'

  resources :documents do
    resource :star, only: [:create, :destroy], controller: 'favourites'

    resources :snapshots, only: :create
    resources :attachements, controller: 'document_attachements', only: [:create, :destroy]
  end

  resources :videos, :links, only: [:create, :destroy]

  resources :photos, only: [:create, :destroy] do
    collection do
      post :finalize
    end
  end

  resources :attachements, controller: 'document_attachements', only: [:create, :destroy]

  resources :investigations do
    resource :star, only: [:create, :destroy], controller: 'favourites'
    member do
      put :publish
      put :unpublish
    end
  end

  resources :snapshots, only: [:create, :destroy, :update] do
    collection do
      post :sort
    end
  end

  resources :organizations, except: :show

  resources :users, except: :show do
    member do
      get :unlock
    end
  end

end

app/models/document.rb
require 'open-uri'
require 'prawn'
require 'prawn/fast_png'
require 'concerns/safe_destroy'
require 'concerns/with_timeline_entry'

class Document < ActiveRecord::Base
  include SafeDestroy

  include WithTimelineEntry

  extend Enumerize

  enumerize :kind, in: [:outgoing, :incoming], default: :outgoing, scope: true, predicates: true
  scope :incoming, -> { with_kind(:incoming) }
  scope :outgoing, -> { with_kind(:outgoing) }

  has_ancestry
  # TODO
  # :cache_depth         Cache the depth of each node in the 'ancestry_depth' column (default: false)
  #                      If you turn depth_caching on for an existing model:
  #                      - Migrate: add_column [table], :ancestry_depth, :integer, :default => 0
  #                      - Build cache: TreeNode.rebuild_depth_cache!

  mount_uploader :pdf, PdfUploader

  belongs_to :response, class_name: 'Document'
  belongs_to :user, counter_cache: true
  belongs_to :author
  belongs_to :investigation
  belongs_to :organization, counter_cache: true

  alias_attribute :cause, :parent
  alias_attribute :cause_id, :parent_id
  alias_attribute :responses, :children

  # Required for `form_for` to work.
  # Fuck you Ancestry...
  def parent_id_before_type_cast
    parent_id
  end

  has_many :snapshots
  has_many :attachements, class_name: 'DocumentAttachement'

  validates :title, presence: true
  validates :description, presence: true
  validates :user, presence: true
  validates :author, presence: true
  validates :investigation, presence: true
  validates :organization, presence: true

  validate :should_contain_snapshot_or_attachement
  validate :cause_in_investigation, if: -> { investigation_id && cause_id }
  validate :cause_is_not_in_subtree, if: -> { cause_id }
  validate :cause_is_earlier_than_self, if: -> { cause_id && document_date }

  scope :latest, -> { order('documents.document_date DESC, documents.id DESC') }
  scope :expired, -> { without_response.outgoing.where('documents.due_date <= ?', Date.current) }
  scope :without_response, -> { where(response_id: nil) }
  scope :with_due_date, -> { where("documents.due_date IS NOT NULL") }

  scope :textual, lambda{|needle|
    needle = "%#{needle}%"
    fields = [
      arel_table[:title],
      arel_table[:description],
      Investigation.arel_table[:title],
      Investigation.arel_table[:description],
      Organization.arel_table[:name],
      Author.arel_table[:name]
    ]

    condition = fields.shift.matches(needle)
    fields.each{|f| condition = condition.or(f.matches needle)}

    includes(:author, :organization, :investigation).where(condition)
  }

  after_create :update_investigation_caches
  after_save   :update_organization_caches
  after_save   :refresh_response

  def responded?
    response.present?
  end

  def caused?
    cause_id.present?
  end

  def overdue?
    return false if due_date.blank?
    due_date < Date.current
  end

  def overtime
    (DateTime.now - due_date.to_datetime).to_i
  end

  def possible_causes
    if investigation
      causes = investigation.documents
      causes = causes.where(["documents.id NOT IN (?)", subtree_ids]) unless new_record?
      causes.where(["documents.document_date IS NULL OR documents.document_date <= ?", document_date]) if document_date
      causes
    else
      Document.none
    end
  end

  def published?
    investigation.publish.active? && investigation.published_until >= document_date
  end

  # two methods for timeline
  def entry_date
    document_date || created_at
  end

  def entry_date_changed?
    document_date_changed?
  end

  private

  def update_investigation_caches
    investigation.cache_latest_document!
  end

  def update_organization_caches
    organization.cache_investigations_counter!
  end

  def refresh_response
    if parent && parent.response_id.blank?
      parent.update_attribute(:response_id, id)
    end

    p = Document.new(ancestry: ancestry_was).parent
    if ancestry_was && p.response_id == id
      p.update_attribute(:response_id, p.responses.first.try(:id))
    end
  end

  def possible_cause_ids
    new_record
  end

  def should_contain_snapshot_or_attachement
    if snapshots.empty? && attachements.empty?
      errors.add(:base, :no_snapshot_or_attachement)
    end
  end

  def cause_in_investigation
    errors.add(:cause_id, :not_in_investigation) unless investigation.documents.exists?(cause_id)
  end

  def cause_is_not_in_subtree
    errors.add(:cause_id, :cause_exists_in_subtree) if (!new_record? && subtree_ids.include?(cause_id))
  end

  def cause_is_earlier_than_self
    errors.add(:document_date, :document_dated_before_cause) if (cause.document_date && cause.document_date > self.document_date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  enumerize :role, in: [:lawyer, :admin], default: :lawyer, predicates: true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :lockable, :recoverable

  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true

  has_one :author
  has_many :documents
  has_many :favourites
  has_many :investigations

  after_create :create_author

  def active_for_authentication?
    super && !blocked?
  end

  private

  def create_author
    Author.create!(name: name, user_id: id)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_filter :authenticate_user!, except: :show
  before_filter :set_collections, only: :index
  before_filter :load_and_check_permissions, only: :show

  respond_to :html

  def index
    @filter = DocumentsFilter.new(params[:f], @favourite_ids)
    @sorter = DocumentsSorter.new(params[:s])

    @documents = @sorter.apply(@filter.apply).page(params[:page])

    render layout: 'index'
  end

  def new
    @document_form = DocumentForm.new(user: current_user)
    @document_form.populate(params)
  end

  def create
    @document_form = DocumentForm.new(user: current_user)
    @document_form.attributes = document_params
    @document_form.save

    log_validation(@document_form)

    respond_with @document_form
  end

  def edit
    @document_form = DocumentForm.new(find_document)
  end

  def update
    @document_form = DocumentForm.new(find_document)
    @document_form.attributes = document_params
    @document_form.save

    log_validation(@document_form)

    respond_with @document_form
  end

  def show
    @snapshots = SnapshotDecorator.decorate_collection(@document.snapshots.sorted)

    respond_to do |format|
      format.html
      if user_signed_in?
        format.pdf { redirect_to @document.pdf.prepared_url }
      end
    end
  end

  def destroy
    document = find_document

    if !document.responded? && (document.user == current_user || current_user.admin?)
      document.safe_destroy
    end

    redirect_to :documents
  end

  private

  def set_collections
    @favourite_ids  = current_user.favourites.documents.pluck(:entry_id)
    @investigations = Investigation.all.pluck(:title, :id)
    @authors        = Author.all.pluck(:name, :id)
    @organizations  = Organization.all.pluck(:name, :id)
  end

  def find_document
    Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :description, :investigation_id, :user_id, :organization_id, :document_date, :due_date, :ancestry, :cause_id, :author_id, :kind, :final, :renew_investigation_publish, snapshot_ids: [], attachement_ids: [])
  end

  def load_and_check_permissions
    @document = find_document

    unless @document.published? || user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def log_validation(document)
    return if document.errors.blank?

    begin
      logger = Logger.new(Rails.root.join("log/validation.log"))
      logger.info "documents: #{current_user.id}##{current_user.email}: #{document.errors.inspect}"
    ensure
      logger.close
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_attachement.html.slim
li.document-attachment(
  id="attachement_#{attachement.id}"
  data-id=attachement.id
  role="list-item"
)
  =' link_to attachement.filename, attachement.file.url, target: '_blank'
  = link_to "[x]", attachement_path(attachement), method: :delete, remote: true, role: "remove-link"

app/views/documents/_attachements_aside.slim
- if @document_form.new_record?
  - scope = @document_form.snapshots.sort_by{|x| x.number}
- else
  - scope = @document_form.snapshots.sorted

.document-attachments
  .document-attachments-title
    | Вложения

  ul.document-attachements-list(role="attachements-list")
    - @document_form.attachements.each do |s|
      = render 'attachement', attachement: s

  .document-attachements-progress
    | Загрузка&nbsp;
    i 100%

  .actions
    a.add-document-attachement#upload_attachement href='#'
      | Добавить…

app/views/documents/_documents_table.html.slim
- if defined?(@filter)
  .list-filter.documents-filter
    = simple_form_for @filter.filterer, as: :f, url: documents_path, method: :get do |f|
      fieldset.list-filter-slider-block@slider
        = image_tag 'icons/slider.png', role: 'handle', class: 'handle', height: 28, width: 28
        = f.input :kind,
                :as => :radio_buttons,
                :required => false,
                :label => false,
                :wrapper_class => 'radio-slider list-filter-slider' do
          = f.collection_radio_buttons  :kind, [['', 'Все типы'], ['incoming', 'Входящий'], ['outgoing', 'Исходящий']], :first, :last, item_wrapper_tag: nil do |b|
            - content_tag :span, role: 'entry', class: "radio-slider-item is-#{b.value}" do
              - b.radio_button + b.label


        = f.input :props,
                :as => :check_boxes,
                :required => false,
                :label => false,
                :wrapper_class => 'list-filter-filter-buttons' do |b|
          = f.collection_check_boxes  :props, [['marked', 'Отмеченные'], ['no_answer', 'Нет ответа'], ['expired', 'Просроченные']], :first, :last, item_wrapper_tag: nil do |b|
            - content_tag :span, class: "is-#{b.value}" do
              - b.check_box + b.label(class: "toggled-button filter-button")

        .list-filter-search-form
          = f.input :title, as: :string, required: false, label: false, placeholder: 'Поиск документов'
          = f.submit value: ''

      fieldset.list-filter-form-block
        = f.input :organization_id, as: :custom_select, required: false, label: 'Организация', collection: @organizations
        = f.input :investigation_id, as: :custom_select, required: false, label: 'Дело', collection: @investigations
        = f.input :user_id, as: :custom_select, required: false, label: 'Автор', collection: @authors

        = f.input :creation_period, as: :date_range, label: 'Дата создания', required: false
        = f.input :period, as: :date_range, label: 'Дата документа', required: false
        = f.input :with_due_date, as: :boolean, label: "С датой истечения", required: false

    .list-filter-total
      | Показано документов: <strong>#{@filter.counters.total}</strong> (#{@filter.counters.incoming} входящих, #{@filter.counters.outgoing} исходящих)

table.index-list.document-list
  thead
    tr
      th.is-star
      th.is-icon
        .icon-wrapper
      th.is-doc class=sort_class?('title')
        a href=sort_by('title')
          | Документ
      th.is-organization class=sort_class?('organization')
        a href=sort_by('organization')
          | Организация
      th.is-case class=sort_class?('investigation')
        a href=sort_by('investigation')
          | Дело
      th.is-author class=sort_class?('author')
        a href=sort_by('author')
          | Автор
      th.is-uploaded class=sort_class?('documents.document_date')
        a href=sort_by('documents.document_date')
          | Дата на документе
      th.is-uploaded class=sort_class?('documents.created_at')
        a href=sort_by('documents.created_at')
          | Загружен
      th.is-answered class=sort_class?('due_date')
        a href=sort_by('due_date')
          | Срок ответа

  tbody
    - @documents.each do |document|
      tr class=("is-#{document.kind}")
        td.is-star
          - if defined?(@favourite_ids)
            = star document, 'documents', @favourite_ids.include?(document.id)
            a.add-connected-document href=new_document_path(cause_id: document.id)
        td.is-icon
        td.is-doc
          a.table-document-title href=document_path(document)
            = document.title
          .table-document-description
            = truncate document.description, length: 45
        td.is-organization
          = document.organization.name
        td.is-case
          = document.investigation.title
        td.is-author
          = document.user.name
        td.is-uploaded
          = l document.document_date.to_date, format: :short
        td.is-uploaded
          = l document.created_at.to_date, format: :short
        td.is-answered class=('responded' if document.responded?) class=('late' if document.overdue?)
          - if document.due_date
            = l document.due_date, format: :short
          - else
            span.spacer
              | &mdash;

app/views/documents/_form.html.slim
= simple_form_for @document_form, as: :document, html: {'data-document' => @document_form.id, 'data-investigation-published' => @document_form.investigation.try(:published_until?)} do |f|
  - if f.object.errors[:base].any?
    .errors
      | При сохранении возникли ошибки:
      ul
        - f.object.errors[:base].each do |e|
          li= e

  fieldset.document-properties
    = f.input :kind,
            :collection => [['incoming', 'Входящий'], ['outgoing', 'Исходящий']],
            :label_method => :last,
            :value_method => :first,
            :as => :radio_buttons,
            :checked => (f.object.kind or 'incoming'),
            :required => false,
            :label => false

    = f.input :document_date, as: :datepicker
    = f.input :due_date, as: :datepicker

    .properties-checkboxes
      = f.input :final, input_html: { role: "document-is-final" }
      = f.input :renew_investigation_publish, as: :boolean, wrapper_html: { role: "document-renew-investigation-publish" }

  = f.input :title, as: :string, input_html: { size: 50 }
  = f.input :description, as: :text

  = f.input :organization_id, as: :select, collection: @document_form.organizations_list, required: false, hint: "выберите из списка, либо введите новое наименование и нажмите Enter"
  = f.error :organization

  = f.input :investigation_id, as: :select, collection: @document_form.investigations_list, required: false, hint: "выберите из списка, либо введите новое наименование и нажмите Enter"
  = f.error :investigation

  = f.input :author_id, as: :select, collection: @document_form.authors_list, required: false, hint: "выберите из списка, либо введите новое наименование и нажмите Enter"
  = f.error :author

  - if f.object.new_record?
    .document-snapshot-ids
      - f.object.snapshots.each do |s|
        = f.hidden_field :snapshot_ids, multiple: true, value: s.id

    .document-attachement-ids
      - f.object.attachements.each do |s|
        = f.hidden_field :attachement_ids, multiple: true, value: s.id

  fieldset.related-document
    = f.input :cause_id, hint: "список документов, доступных для выбора, зависит от выбранного дела" do
      = f.select :cause_id, f.object.possible_causes.map {|x| [x.title, x.id.to_s, {'data-kind' => x.kind, 'data-date' => x.document_date}] }, {include_blank: true}, {role: 'related-doc-select'}

  - if f.object.cause_id.blank? && f.object.new_record?
    .related-warning(role="related-doc-warning")
      | Вы уверены, что хотите загрузить документ без ответа?

  .actions
    = f.submit 'Сохранить изменения', class: 'big-green-button is-compact'

#attachement_upload_box
#snapshot_upload_box

app/views/documents/_related_doc.html.slim
.related-document class="is-#{document.kind} #{current ? 'is-current' : ''}"
  .related-document-title
    = link_to_unless_current(document.title, document_path(document))
  .related-document-date
    = l document.document_date

app/views/documents/_snapshot.html.slim
li.document-attachment(
  id="snapshot_#{snapshot.id}"
  data-id=snapshot.id
  data-public-image=snapshot.public_scan.url(:preview)
  data-original-image=snapshot.original_scan.url(:preview)
  role="list-item"
)
  = image_tag snapshot.original_scan.url(:thumb)
  .document-snapshot-controls
    = link_to '', snapshot.original_scan.url(:preview), rel: "documents", class: 'document-snapshot-preview'
    = link_to '', 'javascript:;', method: :delete, class: 'document-snapshot-editor', role: 'snapshot-editor-button'
    = link_to '', snapshot_path(snapshot), remote: true, method: :delete, class: 'document-snapshot-remove', role: 'remove-link'

app/views/documents/_snapshots_aside.slim
.document-aside-error(role="aside-validation-error")
  | Необходимо загрузить хотя бы один скан или вложение.

- if @document_form.new_record?
  - scope = @document_form.snapshots.sort_by{|x| x.number}
- else
  - scope = @document_form.snapshots.sorted

.document-attachments
  .document-attachments-title
    | Содержимое документа
  .hint
    | Загрузите файл PDF со всеми страницами,
    | или загружайте по одной странице изображениями в формате JPEG или PNG.

  ul.document-snapshots-list(role="snapshots-list")
    - scope.each do |s|
      = render 'snapshot', snapshot: s

  .document-snapshots-progress
    | Загрузка&nbsp;
    i 100%

  .actions
    a.add-document-snapshot#attach href='#'
      | Добавить…

app/views/documents/edit.html.slim
article.is-form.is-document-form.is-edit-form

  = link_to 'Вернуться к списку документов', documents_path, class: 'link-back'

  h1.form-title
    | Редактирование документа

  = render 'form'

.document-form-side data-document=@document_form.id
  = render 'snapshots_aside'
  = render 'attachements_aside'

app/views/documents/index.html.slim
- content_for :add do
  .big-green-button.add-new-object.is-new-document
    = link_to 'Добавить документ', new_document_path

= render 'documents/documents_table'
= paginate @documents

app/views/documents/new.html.slim
article.is-form.is-document-form

  = link_to 'Вернуться к списку документов', documents_path, class: 'link-back'

  h1.form-title
    | Добавление документа

  = render 'form'

.document-form-side
  = render 'snapshots_aside'
  = render 'attachements_aside'

app/views/documents/show.html.slim
article.is-document
  = link_to 'Документы', documents_path, class: 'link-back'

  h1.document-title class="is-#{@document.kind}"
    = @document.title
    span.document-date
      = l @document.document_date

  p.document-description= auto_link @document.description

  dl.document-properties
    dt Дата на документе:
    dd= l @document.document_date

    dt Загружен:
    dd= l @document.created_at.to_date

    dt Срок ответа:
    dd
      - if @document.due_date
        = l @document.due_date
        - if @document.responded?
          i (ответ отправлен)
      - else
        span.spacer
          | &mdash;

    dt Организация:
    dd= link_to @document.organization.name, @document.organization

    dt Дело:
    dd= link_to @document.investigation.title, @document.investigation

    dt Автор:
    dd= @document.author.name

  - @snapshots.each do |s|
    a href=s.scan.url target="_blank"
      img.snapshot src=s.scan.url(:preview)

.document-side
  - if user_signed_in?
    ul.document-controls
      li.document-control.is-edit
        = link_to 'Редактировать', edit_document_path(@document), class: "action"
      - if false
        li.document-control.is-duplicate
          = link_to 'Создать копию', '#', class: "action"
      - if @snapshots.any?
        li.document-control.is-download
          = link_to 'Скачать скан документа', document_path(@document, format: :pdf), class: "action"
          | PDF
      li.document-control.is-connect
        = link_to 'Добавить связанный', new_document_path(cause_id: @document.id), class: "action"

      - if @document.user == current_user || current_user.admin?
        li.document-control.is-delete
          - if !@document.responded?
            = link_to 'Удалить документ', @document, method: :delete, data: {confirm: "Вы уверены?"}, class: "action"
          - else
            = link_to 'Как удалить этот документ?', '#', role: "delete-instructions-link", class: "action"
          - if @document.responded?
            .side-control-popover(role="delete-instructions-popover")
              | Для того, чтобы удалить текущий документ, необходимо разорвать связь между ним и тем документом, который был получен в ответ.
              .popover-linked
                = link_to @document.response.title, @document.response
                span= l @document.response.document_date, format: :thread_short

  .related-documents
    - if @document.cause
      = render 'related_doc', document: @document.cause, current: false

    = render 'related_doc', document: @document, current: true

    - @document.responses.each do |d|
      = render 'related_doc', document: d, current: false