config/routes.rb
Kbk::Application.routes.draw do
  devise_for :users

  root to: 'investigations#index'

  resources :documents do
    resource :star, only: [:create, :destroy], controller: 'favourites'

    resources :snapshots, only: :create
    resources :attachements, controller: 'document_attachements', only: [:create, :destroy]
  end

  resources :videos, :links, only: [:create, :destroy]

  resources :photos, only: [:create, :destroy] do
    collection do
      post :finalize
    end
  end

  resources :attachements, controller: 'document_attachements', only: [:create, :destroy]

  resources :investigations do
    resource :star, only: [:create, :destroy], controller: 'favourites'
    member do
      put :publish
      put :unpublish
    end
  end

  resources :snapshots, only: [:create, :destroy, :update] do
    collection do
      post :sort
    end
  end

  resources :organizations, except: :show

  resources :users, except: :show do
    member do
      get :unlock
    end
  end

end

app/views/layouts/application.html.slim
html
  head
    title Фонд Борьбы с Коррупцией
    link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    - if controller_name == "documents" && user_signed_in?
      = render 'shared/snapshot_editor'

    .wrapper
      = yield

    - if current_user
      footer#main-footer
        .wrapper
          = render 'shared/footer_links'

app/views/layouts/devise.html.slim
html
  head
    title Фонд Борьбы с Коррупцией
    link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    .login-wrapper
      = yield

    - if current_user
      footer#main-footer
        .wrapper
          = render 'shared/footer_links'

app/views/layouts/index.html.slim
html
  head
    title Фонд Борьбы с Коррупцией
    link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    .wrapper
      header#main-header
        h1#main-logo
          = link_to_unless_current "Дела ФБК", :root
        navigation#main-navigation
          ul
            li class=('is-active' if controller_name == 'investigations')
              = link_to 'Дела', investigations_path
            li class=('is-active' if controller_name == 'documents')
              = link_to 'Документы', documents_path
            li class=('is-active' if controller_name == 'organizations')
              = link_to 'Организации', organizations_path
            li class=('is-active' if controller_name == 'users')
              = link_to 'Сотрудники', users_path
        = yield :add

      = yield

    footer#main-footer
      .wrapper
        = render 'shared/footer_links'